name = "MathlibDemo"
defaultTargets = ["MathlibDemo", "TheLeanFile"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.27.0"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.27.0"

[[lean_lib]]
name = "MathlibDemo"

[[lean_lib]]
name = "TheLeanFile"

[[lean_exe]]
name = "mkdoc"
root = "Main"
