name = "MathlibDemo"
defaultTargets = ["MathlibDemo", "TheLeanFile"]
moreLeancArgs = ["-O0"]

[leanOptions]
pp.unicode.fun = true
doc.verso = true

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "html-handler"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.29.0"

# Used for compybox demo
[[require]]
name = "lean4export"
scope = "leanprover"
rev = "v4.29.0"

# Used for compybox demo
[[require]]
name = "ModuleConstants"
path = "./ModuleConstants"

[[lean_lib]]
name = "MathlibDemo"

[[lean_lib]]
name = "TheLeanFile"
