name = "verso-nightly"
version = "0.1.0"
moreLeancArgs = ["-O0"]
defaultTargets = ["MakeVerso"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "nightly-testing"

[[lean_lib]]
name = "MakeVerso"

