name = "verso-nightly"
version = "0.1.0"
moreLeancArgs = ["-O0"]
defaultTargets = ["TheLeanFile"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "html-handler"

[[lean_lib]]
name = "TheLeanFile"


